name: Sync to Cloudflare R2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate output files
        run: |
          mkdir -p output
          echo "This is a test result." > output/result.txt
          echo "#EXTM3U" > output/result.m3u

      - name: Check file permissions
        run: |
          ls -l output/
          chmod 644 output/*.txt

      - name: Uninstall existing AWS CLI
        run: |
          if command -v aws &> /dev/null; then
            sudo rm -rf /usr/local/aws-cli
            sudo rm -rf /usr/local/bin/aws
          fi

      - name: Install latest AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O
          unzip awscli-exe-linux-x86_64.zip
          sudo ./aws/install --update

      - name: Configure AWS CLI for R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto
          aws configure set default.s3.endpoint_url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com
          aws configure set max_attempts 5  # 控制全局重试次数

      - name: Test R2 connectivity
        run: |
          aws s3 ls s3://${{ secrets.R2_BUCKET }} --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com || true

      - name: Sync result.txt to R2
        run: |
          aws s3 cp output/result.txt s3://${{ secrets.R2_BUCKET }}/iptv.txt \
            --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com \
            --acl public-read \
            --debug

      - name: Sync result.m3u to R2
        run: |
          aws s3 cp output/result.m3u s3://${{ secrets.R2_BUCKET }}/iptv.m3u \
            --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com \
            --acl public-read \
            --debug
