name: Sync Files to Cloudflare R2
on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

jobs:
  upload-files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        run: |
          sudo pip install --upgrade awscli
          aws --version

      - name: Generate Sample Files
        run: |
          mkdir -p ./output
          echo "This is result $(date)" > ./output/result.txt
          echo "Another file content" > ./output/result.m3u
          ls -l ./output

      - name: Validate Files
        run: |
          required_files=("result.txt" "result.m3u")
          for file in "${required_files[@]}"; do
            if [ ! -f "./output/$file" ]; then
              echo "❌ Error: $file not found"
              exit 1
            fi
          done
          echo "✅ All files verified"

      - name: Upload Files
        run: |
          aws s3 cp ./output/ s3://zhou/ \
            --endpoint-url="$R2_ENDPOINT" \
            --region auto \
            --recursive \
            --exclude "*" \
            --include "result.*" \
            --retries 5

      - name: Verify Upload
        run: |
          aws s3 ls s3://zhou/ \
            --endpoint-url="$R2_ENDPOINT" \
            --human-readable
