name: Sync to Cloudflare R2

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 选项：你可以根据需要修改为其他分支（可选）

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Uninstall existing AWS CLI (if any)
        run: |
          if command -v aws &> /dev/null; then
            sudo rm -rf /usr/local/aws-cli
            sudo rm -rf /usr/local/bin/aws
          fi

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O
          unzip awscli-exe-linux-x86_64.zip
          sudo ./aws/install

      - name: Configure AWS CLI for R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto
          aws configure set default.s3.endpoint_url https://your-account-id.r2.cloudflarestorage.com  # 用实际的账户ID替换

      - name: Sync result.txt to R2
        run: |
          aws s3 cp result.txt s3://${{ secrets.R2_BUCKET }}/iptv.txt --acl public-read
