name: Sync to Cloudflare R2

on:
  workflow_dispatch:   # 允许手动触发
  push:
    branches:
      - main           # 仅在 main 分支推送时触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate output files
        run: |
          mkdir -p output
          # 生成测试文件（替换为您实际的文件生成逻辑）
          echo "This is a test result." > output/result.txt
          echo "#EXTM3U" > output/result.m3u
          # 生成一个额外的小文件用于测试上传
          echo "test" > output/test.txt

      - name: Check file permissions
        run: |
          ls -l output/  # 检查文件权限
          chmod 644 output/*.txt  # 确保文件可读

      - name: Uninstall existing AWS CLI (if any)
        run: |
          if command -v aws &> /dev/null; then
            sudo rm -rf /usr/local/aws-cli
            sudo rm -rf /usr/local/bin/aws
          fi

      - name: Install latest AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O
          unzip awscli-exe-linux-x86_64.zip
          sudo ./aws/install --update  # 强制更新到最新版本

      - name: Configure AWS CLI for R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto
          aws configure set default.s3.endpoint_url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com  # 替换为你的账户ID

      - name: Test R2 connectivity (Debug)
        run: |
          aws s3 ls s3://${{ secrets.R2_BUCKET }} --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com || true

      - name: Upload test.txt (Verify setup)
        run: |
          aws s3 cp output/test.txt s3://${{ secrets.R2_BUCKET }}/test.txt \
            --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com \
            --acl public-read \
            --retries 5 \
            --debug

      - name: Sync result.txt to R2
        run: |
          aws s3 cp output/result.txt s3://${{ secrets.R2_BUCKET }}/iptv.txt \
            --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com \  # 显式指定端点
            --acl public-read \
            --retries 5 \        # 增加重试次数
            --debug              # 输出详细日志

      - name: Sync result.m3u to R2
        run: |
          aws s3 cp output/result.m3u s3://${{ secrets.R2_BUCKET }}/iptv.m3u \
            --endpoint-url https://fdfc48442676ca0e6b49dcef9d73afec.r2.cloudflarestorage.com \
            --acl public-read \
            --retries 5 \
            --debug
