name: Sync Files to Cloudflare R2
on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

jobs:
  upload-files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean existing installations
        run: |
         sudo apt remove awscli -y || true  # 忽略未安装的情况
         sudo pip uninstall awscli -y || true
         sudo rm -rf /usr/local/aws-cli
         sudo rm -f /usr/local/bin/aws

      - name: Install AWS CLI v2 with update
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version

      - name: Generate Sample Files
        run: |
          mkdir -p ./output
          echo "This is result $(date)" > ./output/result.txt
          echo "Another file content" > ./output/result.m3u
          ls -l ./output

      - name: Validate Files
        run: |
          required_files=("result.txt" "result.m3u")
          for file in "${required_files[@]}"; do
            if [ ! -f "./output/$file" ]; then
              echo "❌ Error: $file not found"
              exit 1
            fi
          done
          echo "✅ All files verified"

      - name: Upload Files
        run: |
          aws s3 cp ./output/ s3://zhou/ \
            --endpoint-url="$R2_ENDPOINT" \
            --region auto \
            --recursive \
            --exclude "*" \
            --include "result.*" \

      - name: Verify Upload
        run: |
          aws s3 ls s3://zhou/ \
            --endpoint-url="$R2_ENDPOINT" \
            --human-readable
